

<div class="modal" id="studioDetailsModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">רשומים לשיעור</h4>
      </div>
      <div class="modal-body">

       <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>שם פרטי</th>
            <th>שם משפחה</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="subsList">

        </tbody>

        </table>





       
      </div>
    </div>
  </div>
</div>






<div class="modal" id="newStudio">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">הוספת שיעור סטודיו</h4>
      </div>
      <div class="modal-body">
         <form class="form-horizontal" id="studioForm" method="post">
                    <div class="form-group row">
                    <div class="col-md-offset-3 col-md-6">
                      <label for="name" class="control-label">שם השיעור:</label>
                        <input type="text" id="name" name="name" class="form-control input-sm" required>
                        </div>
                    </div>
                  <div class="form-group row">
                  <div class="col-md-offset-3 col-md-6">
                      <label class="control-label" >מדריך:</label>
                          <select name="trainer"  class="form-control input-sm" required>
                              <option value="" display selected style='display:none;'>בחר מהרשימה</option>
                                  <?php 

                              foreach ($trainersList as $key => $value) {
                               echo '<option value="'.$value['id'].'">'.$value['firstName'].' '.$value['lastName'].'</option>';
                                }

                                  ?>
                              </select>
                              </div>
                     </div>
                      <div class="form-group row">
                      <div class="col-md-offset-3 col-md-6">
                      <label class="control-label" >קטגוריה:</label>
                          <select name="catId"  class="form-control input-sm" required>
                              <option value="" display selected style='display:none;'>בחר מהרשימה</option>
                                  <?php 

                              foreach ($catList as $key => $value) {
                               echo '<option value="'.$value['id'].'">'.$value['name'].'</option>';
                                }

                                  ?>
                              </select>
                              </div>
                     </div>
                  <div class="form-group row">
                  <div class="col-md-offset-3 col-md-6">
                    <label class="control-label">ימים בשבוע:</label>
                    <div class="options">
                   <label for="day1" class="control-label">א</label>
                   <input type="checkbox" data-day="א" value="ראשון" name="day1" required>
                  <label for="day2" class="control-label">ב</label>
                  <input type="checkbox" data-day="ב" value="שני" name="day2" required>
                   <label for="day3" class="control-label">ג</label>
                   <input type="checkbox" data-day="ג" value="שלישי" name="day3" required>
                    <label for="day4" class="control-label">ד</label>
                   <input type="checkbox" data-day="ד" value="רביעי" name="day4" required>
                    <label for="day5"  class="control-label">ה</label>
                   <input type="checkbox" data-day="ה" value="חמישי" name="day5" required>
                   <label for="day6" class="control-label">ו</label>
                   <input type="checkbox"  data-day="ו" value="שישי" name="day6" required>
                    <label for="day7" class="control-label">ש</label>
                   <input type="checkbox"  data-day="ש" value="שבת" name="day7" required>
                    </div>
                    </div>
                  </div>

              <input type="hidden" name="postFunction" value="addStudio">
              </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">סגור</button>
        <input type="submit" class="btn btn-primary" form="studioForm" value="הוספת שיעור">
      </div>
    </div>
  </div>
</div>



<div class="col-md-10">



  <div class="row">
    <?php  foreach ($catList as $key => $cat) { ?>
<div class="col-md-4">
<div class="panel panel-default">
  <div class="panel-heading">
    <?=  $cat['name']  ?>
  </div>
  <div class="panel-body">
  <ul class="list-group">
    <?php  
        foreach ($studioLessons as $key => $studio) {

              if ($studio->getCatId()==$cat['id'])
              {

         ?>
            
               
            <li class="list-group-item text-center">
           <?php
                echo $studio->getName();

           ?>
            <span class="badge studioBtn" style="cursor:pointer"><span class="glyphicon glyphicon-chevron-down"></span></span>
            </li>

            <div class="well well-sm studioDetails" data-status="close" style="overflow: hidden;height: 0px;display: none;margin-bottom: 0px;min-height: auto;padding: 0px;" >


    <?php 


                foreach ($trainersList as $key => $trainer) {
                  if ($trainer['id']==$studio->getTrainerId())
                    echo "<h5 class='text-center'>מדריך: ".$trainer['firstName']." ".$trainer['lastName']."</h5>";
                }
                echo "<div class='text-center showRegBtn' data-studio-id='".$studio->getStudioId()."'><a href='#'>מנויים רשומים</a></div><hr>"

      ?>
         <table class="table table-striped">
           <thead>
          <tr>
            <th class="text-center">יום</th>
            <th class="text-center">שעה</th>
         </tr>
        </thead>
        <tbody>
      <?php


     foreach ($studio->getLessons() as $key => $lesson) { 
                 
                  if ($studio->getStudioId()==$lesson->getStudioId()){
                   ?>
                   
                   
              <tr>
                <td class="text-center">
                   <?= $lesson->getDay();?>
                </td>
                <td class="text-center">
                    <?= $lesson->getTime();?>
                </td>
                </tr>  


                   



                   <?php     





                    } 
                  }

                echo " </tbody></table></div>";  
               }

             }

        ?>

      </ul>
  </div>
</div>
</div>

<?php  }   ?>
</div>


  </div>

</div>


<script type="text/javascript">
  




$(document).ready(function () {




 $(".showRegBtn").click(function(){

    $("#subsList").attr("data-studio-id" , $(this).data('studio-id'));

    $.post("index.php?section=studio&action=getRegsByStudio",{
       studioId: $(this).data('studio-id')

    }, function (data, status){
      
            data =JSON.parse(data);
            console.log(data);
          if (data!=false){
           $("#subsList").html("");

           for (i=0; i<data.length ; i++){
             $("#subsList").append("<tr id='"+data[i]['id']+"'><td>"+(i+1)+"</td><td>"+data[i]['firstName']+"</td><td>"+data[i]['lastName']+"</td><td><span class='glyphicon glyphicon-remove-circle remove-sub' style='cursor:pointer' aria-hidden='true'></span></td></tr>");
           }
         }else{
           $("#subsList").html("אין מנויים הרשומים לשיעור הסטודיו");

         }

    });



$("#studioDetailsModal").modal("show");

 })



$("body").on("click" , ".remove-sub" , function(){

  row = $(this).closest( $("tr"));

if (confirm("האם להסיר את המנוי משיעורי הסטודיו?")){
   
    $.post("index.php?section=studio&action=removeSubFromStudio",{
       studioId: $(this).closest( $("#subsList")).attr('data-studio-id'),
       subId: $(this).closest( $("tr")).attr('id')

    }, function (data, status){
        if (data==1){
          row.fadeOut();
          setTimeout(function(){
            row.remove();
          }, 1000)
          
        }

    });



}

})







  $("#studioForm input[type='checkbox']").click(function (){


       if ($(this).is(':checked'))
       { 
            $("#studioForm").append('<div class="form-group row"><div class="col-md-offset-3 col-md-2"><label for="name" data-checkId="'+$(this).val()+'" class="control-label">יום '+$(this).data('day')+':</label></div><div class="col-md-3"><input type="time" name="time_'+$(this).attr('name')+'"class="form-control input-sm" required></div></div>');
        }
        else
        {

          $( "*[data-checkId='"+$(this).val()+"']" ).parent().parent().remove();

        }
    });


    var requiredCheckboxes = $('.options :checkbox[required]');
    requiredCheckboxes.change(function(){
        if(requiredCheckboxes.is(':checked')) {
            requiredCheckboxes.removeAttr('required');
        } else {
            requiredCheckboxes.attr('required', 'required');
        }
    });



    $(".studioBtn").click(function(){

      var studioDetails = $(this).parent().next(".studioDetails");

      if (studioDetails.data("status") == "close"){
          $(this).removeClass("arrow-down");
          $(this).addClass("arrow-up");

        
        studioDetails.show();

        studioDetails.animate({height: studioDetails.get(0).scrollHeight , padding:"9px"})
        studioDetails.data("status" , "open")
      }
      else{
          $(this).removeClass("arrow-up");
          $(this).addClass("arrow-down");

        studioDetails.data("status" , "close")

        studioDetails.animate({height: "0px",padding:"0px" }, function(){
          $(this).hide();
        })

      }





    });


});






</script>


<style type="text/css">
  

.arrow-up{
    animation-timing-function: linear;
    animation-name: arrow-change-up;
    animation-duration: 0.3s;
    animation-fill-mode: forwards;
}

@keyframes arrow-change-up {
    to {transform: rotate(180deg);}
}


@keyframes arrow-change-down {
    to {transform: rotate(180deg);}
}

.arrow-down{
    animation-timing-function: linear;
    animation-name: arrow-change-down;
    animation-duration: 0.3s;
    animation-direction: reverse;
}

</style>