<nav class="navbar navbar-default col-md-10">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">דוחות</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">דוחות</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">מנויים <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
        <li><a href="index.php?section=reports&action=showReport&num=1">מנויים לפי תאריך רישום</a></li>
        <li><a href="index.php?section=reports&action=showReport&num=2">מנויים לפי תאריך סיום מנוי</a></li>
        <li><a href="index.php?section=reports&action=showReport&num=3">התפלגות גילאים</a></li>
        <li><a href="index.php?section=reports&action=showReport&num=4">התפלגות מגדרית</a></li>
          </ul>
        </li>
      </ul>
      
    </div>
  </div>
</nav>