<div class="col-sm-3 col-md-4 col-md-offset-1">
<div class="panel panel-default">
  <div class="panel-heading">מנויים</div>
  <div class="panel-body">

    <?php include("views/reports/subs/listReportsSubs.phtml"); ?>

  </div>
</div>
</div>

<div class="col-sm-3 col-md-4">
<div class="panel panel-default">
  <div class="panel-heading">סטודיו</div>
  <div class="panel-body">
    <?php include("views/reports/studios/listReportsStudio.phtml"); ?>
  </div>
</div>


</div>

