    <ul class="list-group">
  <a href="index.php?section=reports&action=showReport&num=1" class="list-group-item">
    מנויים לפי תאריך רישום
  </a>
  <a href="index.php?section=reports&action=showReport&num=2" class="list-group-item">
    מנויים לפי תאריך סיום מנוי
  </a>
  <a href="index.php?section=reports&action=showReport&num=3" class="list-group-item">
    התפלגות גילאים
  </a>
  <a href="index.php?section=reports&action=showReport&num=4" class="list-group-item">
    התפלגות מגדרית
  </a>
</ul>