<div class="col-md-10">
<div class="panel panel-default">
   <div class="panel-heading">
    <ul class="breadcrumb" style="background:none; padding:0px; margin:0px;">
  <li><a href="index.php?section=reports">דוחות</a></li>
  <li><a href="index.php?section=reports&action=reportsStudiosMain"><?php echo $category ?></a></li>
  <li class="active"> <?php echo $reportName ?></li>
</ul>
  </div>
  <div class="panel-body">

  </div>
</div>
</div> 