
<div class="container-fluid col-sm-4 col-sm-offset-4">
<div class="page-header text-center"><img src="logo.png" width="200" height="auto" alt="logo" />
</div>

<form class="form-horizontal form-group" action="index.php?action=login" method="post" id="login">
<div class="form-group">
  <input type="text" class="form-control col-sm-offset-3 col-sm-7" name="userName" placeholder="נא להקליד שם משתמש" required>
</div>

<div class="form-group">
  <input type="password" class="form-control col-sm-offset-3 col-sm-7" name="password" placeholder="נא להקליד סיסמא" required>
</div>
        <div class="checkbox col-sm-offset-3">
          <label>
 <input type="checkbox" checked name="check"> השאר מחובר  
          </label>
        </div>
<button type="submit" class="btn btn-primary col-sm-offset-6">התחברות</button>
  
</form>

        
</div>

