<!DOCTYPE html>
<html lang="en">
    <head>
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8" />
        <title>SpaceGym - <?php echo $title; ?></title>
        <link rel="stylesheet" type="text/css" href="libs/bootstrap-3.3.2-dist/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="libs/bootstrap-3.3.2-dist/css/daterangepicker.css">
        <link rel="stylesheet" type="text/css" href="libs/bootstrap-3.3.2-dist/css/bootstrap-rtl.css">
        <link rel="stylesheet" type="text/css" href="libs/animate.css">

        <script src="libs/jquery/jquery-1.11.3.min.js"></script>
        <script src="libs/bootstrap-3.3.2-dist/js/bootstrap.js"></script>
        <script src="libs/bootstrap-3.3.2-dist/js/moment.js"></script>
        <script src="libs/bootstrap-3.3.2-dist/js/daterangepicker.js"></script>

 
    </head>
    <body >
