<nav class="navbar navbar-default col-md-10">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">תוכניות אימונים</a>
    </div>

        <form class="navbar-form navbar-right" role="search" method="get">
        <div class="form-group">
            <input type="hidden" name="section" value="training" /> 
            <input type="hidden" name="action" value="search"/> 
            <div class="input-group">
             <input type="text" class="form-control" name="query"placeholder="הקלד שם או תעדות זהות" required>
                 <span class="input-group-btn">
                  <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span> חיפוש מנוי</button>
                </span>
          </div>
        </div>
      </form>
  </div>
</nav>
