

<div class="col-md-10">
<h3><small>תוצאות חיופש עבור: <?php echo $_GET['query']?></small></h3>
  <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>תעודת זהות</th>
      <th>שם פרטי</th>
      <th>שם משפחה</th>
    </tr>
  </thead>
  <tbody>

<?php 
for ($i=0; $i<count($subs) ;$i++)
{


    echo "<tr class='getSubPrograms' style='cursor:pointer;'>
    <form  method='get'><input type='hidden' name='section' value='training'/>
    <input type='hidden' name='action' value='showSubPrograms'/>
    <input type='hidden' name='id' value='".$subs[$i]['id']."'/>
    <input type='hidden' name='firstName' value='".$subs[$i]['firstName']."'/> 
    <input type='hidden' name='lastName' value='".$subs[$i]['lastName']."'/></form>
    <td>".($i+1)."</td>
    <td>".$subs[$i]['id']."</td>
    <td>".$subs[$i]['firstName']."</td>
    <td>".$subs[$i]['lastName']."</td>
    </tr>";

  
}
?>

  </tbody>
</table> 
</div>


<script type="text/javascript">

$(document).ready(function(){

  $(".getSubPrograms").click(function (){
    $(this).find("form").submit();

  });

});

</script>