<div class="col-md-10">
<h3><small>תוצאות חיופש עבור: <?php echo $_GET['query']?></small></h3>
  <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>שם פרטי</th>
      <th>שם משפחה</th>
      <th>תחילת מנוי</th>
      <th>סיום מנוי</th>
      <th>סטטוס מנוי</th>
    </tr>
  </thead>
  <tbody>

<?php 

for ($i=0; $i<count($subs) ;$i++)
{
    echo "<tr id='".$subs[$i]['id']."' class='showSubDetails' style='cursor:pointer;'>
    <td>".($i+1)."</td>
    <td>".$subs[$i]['firstName']."</td>
    <td>".$subs[$i]['lastName']."</td>
    <td>".date("d-m-Y", strtotime($subs[$i]['dateStart']))."</td>
    <td>".date("d-m-Y", strtotime($subs[$i]['dateEnd']))."</td>";

    if (!$subs[$i]['active'])
      echo '<td><span class="label label-danger">לא פעיל</span></td>';
    else
     echo '<td><span class="label label-success">פעיל</span></td>';

    echo "</tr>";
}
?>

  </tbody>
</table> 
</div>