

<!--last registers table-->
<div class="col-sm-3 col-md-4 col-md-offset-1">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">נרשמים אחרונים</h3>
  </div>
  <div class="panel-body">
   <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>שם מנוי</th>
      <th>תאריך רישום</th>
    </tr>
  </thead>
  <tbody>

<?php 

for ($i=0; $i<count($lastReg) ;$i++)
{
    echo "<tr id='".$lastReg[$i]['id']."' class='showSubDetails ' style='cursor:pointer;'>
    <td>".($i+1)."</td>
    <td>".$lastReg[$i]['name']."</td>
    <td>".$lastReg[$i]['subDate']."</td>
    </tr>";
}
?>

  </tbody>
</table> 
  </div>
</div>
</div>
<!--end table-->

<div class="col-sm-3 col-md-4">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">נרשמים אחרונים</h3>
  </div>
  <div class="panel-body">

  </div>
</div>
</div>




